# Generated by Django 4.0.4 on 2022-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=22)),
                ('apellido', models.CharField(max_length=22)),
                ('cumpleaños', models.DateField()),
                ('camada', models.IntegerField()),
                ('foto', models.ImageField(upload_to='perfiles/alumnos')),
                ('cursos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=22)),
                ('descripcion', models.TextField()),
                ('camada', models.IntegerField()),
                ('cantidad_clases', models.IntegerField()),
                ('inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=22)),
                ('apellido', models.CharField(max_length=22)),
                ('cumpleaños', models.DateField()),
                ('bio', models.TextField()),
                ('camada', models.IntegerField()),
                ('foto', models.ImageField(upload_to='perfiles/profesores/')),
                ('link_linkedin', models.URLField()),
                ('link_git', models.URLField()),
            ],
        ),
    ]
