# Generated by Django 4.0.4 on 2022-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profesores',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254),
        ),
    ]
