# Generated by Django 4.0.4 on 2022-05-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_alumnos_email_profesores_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(upload_to='app_coder/perfiles/alumnos'),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='foto',
            field=models.ImageField(upload_to='app_coder/perfiles/profesores/'),
        ),
    ]
