# Generated by Django 4.0.4 on 2022-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0005_alter_alumnos_foto_alter_profesores_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(upload_to='app_coder/media/perfiles/alumnos'),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='foto',
            field=models.ImageField(upload_to='app_coder/media/perfiles/profesores/'),
        ),
    ]
