# Generated by Django 4.0.4 on 2022-05-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0007_alter_alumnos_foto_alter_profesores_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='portada',
            field=models.ImageField(default='', upload_to='cursos/portadas/'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='tipo',
            field=models.TextField(choices=[('WE', 'Desarrollo WEB'), ('BACKEND', 'Desarrollo BackEnd'), ('DISEÑO', 'Diseño Grafico'), ('DEVOPS', 'DevOps')], default='', max_length=40),
        ),
    ]
