# Generated by Django 4.0.4 on 2022-05-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0008_cursos_portada_cursos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='tipo',
            field=models.TextField(choices=[('WEB', 'Desarrollo WEB'), ('BACKEND', 'Desarrollo BackEnd'), ('DISEÑO', 'Diseño Grafico'), ('DEVOPS', 'DevOps')], default='', max_length=40),
        ),
    ]
