# Generated by Django 4.0.4 on 2022-05-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0009_alter_cursos_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='nota',
            field=models.IntegerField(default='0'),
        ),
    ]
